#!/bin/bash
# Copyright 2017 The Bootkube-CI Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
### Declare colors to use during the running of this script:
declare -r GREEN="\033[0;32m"
declare -r RED="\033[0;31m"
declare -r YELLOW="\033[0;33m"

function echo_green {
  echo -e "${GREEN}$1"; tput sgr0
}
function echo_red {
  echo -e "${RED}$1"; tput sgr0
}
function echo_yellow {
  echo -e "${YELLOW}$1"; tput sgr0
}

source .bootkube_env

## NEW INSTALLATIONS:
for node in $(cat ./deploy-node/nodes); do
  echo -e "Creating demo directory on ${node} in...";
  ssh -o "StrictHostKeyChecking no" -tq ${node} "mkdir ${HOME}/demo";
  ssh -tq ${node} "sudo mv ${HOME}/demo ${BOOTKUBE_DIR}";
  echo -e "Copying Kubernetes node files to ${node}...";
  scp ${BOOTKUBE_DIR}/deploy-node/node-add ${node}:${BOOTKUBE_DIR};
  scp ${BOOTKUBE_DIR}/clean-kubernetes ${node}:${BOOTKUBE_DIR};
  scp ${BOOTKUBE_DIR}/.bootkube_env ${node}:${BOOTKUBE_DIR};
  scp ${BOOTKUBE_DIR}/.bootkube/tls/ca.crt ${node}:${BOOTKUBE_DIR};
  scp ${BOOTKUBE_DIR}/.bootkube/auth/kubeconfig ${node}:${BOOTKUBE_DIR};
  echo -e "Attempting to deploy ${node} as a worker node...";
  ssh -tq ${node} "cd ${BOOTKUBE_DIR}/ && \
    sudo chown root:root ${BOOTKUBE_DIR}/kubeconfig && \
    sudo mkdir -p ${BOOTKUBE_DIR}/backups/ && \
    ./node-add";
done
