#!/bin/bash
# Copyright 2017 The Bootkube-CI Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
### Declare colors to use during the running of this script:
declare -r GREEN="\033[0;32m"
declare -r RED="\033[0;31m"
declare -r YELLOW="\033[0;33m"

function echo_green {
  echo -e "${GREEN}$1"; tput sgr0
}
function echo_red {
  echo -e "${RED}$1"; tput sgr0
}
function echo_yellow {
  echo -e "${YELLOW}$1"; tput sgr0
}

source /opt/demo/.bootkube_env
# VARIABLES USED:
echo_green "\nVariables used during the Helm/Tiller deployment:"
printf "HELM_REPO: ${HELM_REPO}
HELM_REPO_URL: ${HELM_REPO_URL} \n \n"

# CLEANING ANY PREVIOUS HELM/TILLER DEPLOYMENTS:
rm -rf /home/${USER}/.helm
pkill -f 'helm serve'

# BRING UP INFRASTRUCTURE ITEMS:
echo -e -n "Bringing up Tiller and Helm repos..."

### PREPARE HELM:
helm init

### WAIT FOR TILLER TO COME UP:
echo -e -n "Waiting for a ready Tiller pod..."
while true; do
  running_count=$(sudo kubectl --kubeconfig=/etc/kubernetes/kubeconfig get pods -n kube-system --no-headers 2>/dev/null | grep "Running" | grep "tiller" | wc -l)
  ### Expect Tiller pods to be equal or greater than 1:
  if [ "$running_count" -ge 1 ]; then
    break
  fi
  echo -n "."
  sleep 1
done
echo_green "SUCCESS"
echo_green "Tiller Ready!"
echo ""

### WAIT FOR TILLER TO COME UP:
echo -e -n "Starting the Helm server..."
helm serve &
sleep 2
helm repo add ${HELM_REPO} "${HELM_REPO_URL}"
