#!/bin/bash
# Copyright 2017 The Bootkube-CI Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
### Declare colors to use during the running of this script:
declare -r GREEN="\033[0;32m"
declare -r RED="\033[0;31m"
declare -r YELLOW="\033[0;33m"

function echo_green {
  echo -e "${GREEN}$1"; tput sgr0
}
function echo_red {
  echo -e "${RED}$1"; tput sgr0
}
function echo_yellow {
  echo -e "${YELLOW}$1"; tput sgr0
}

### PREPARE THE ENVIRONMENT:
source /opt/demo/.bootkube_env
echo_green "\nVariables used during the Helm deployment:"
printf "OSH_REPO_URL: ${OSH_REPO_URL}
OSH_BRANCH: ${OSH_BRANCH} \n \n"

### CLEAN PREVIOUS DEPLOYMENTS:
echo_yellow "\nCleaning up any previous OpenStack-Helm deployments:"
rm -rf ${BOOTKUBE_DIR}/projects/openstack-helm

### DOWNLOAD: OpenStack-Helm
echo_yellow "\nCloning the OpenStack-Helm repository:"
mkdir -p ${BOOTKUBE_DIR}/projects/
git clone ${OSH_REPO_URL} ${BOOTKUBE_DIR}/projects/openstack-helm && cd ${BOOTKUBE_DIR}/projects/openstack-helm && git checkout ${OSH_BRANCH}

### REMOVE HELM STABLE REPO TO SPEED UP MAKE PROCESS:
echo_yellow "\nRemoving the stable Helm repository to speed up the OpenStack-Helm build process:"
helm repo remove stable

### LINT/PACKAGE/LOAD CHARTS:
echo_yellow "\nLinting, packaging, and uploading charts to the ${HELM_REPO} repository:"
make

### PUT BACK HELM STABLE REPO:
echo_yellow "\nRe-adding the stable Helm repository:"
helm repo add stable https://kubernetes-charts.storage.googleapis.com
