#!/bin/bash
# Copyright 2017 Charter DNA Team (CTEC).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
### Declare colors to use during the running of this script:
declare -r GREEN="\033[0;32m"
declare -r RED="\033[0;31m"
declare -r YELLOW="\033[0;33m"

function echo_green {
  echo -e "${GREEN}$1"; tput sgr0
}
function echo_red {
  echo -e "${RED}$1"; tput sgr0
}
function echo_yellow {
  echo -e "${YELLOW}$1"; tput sgr0
}

source /opt/demo/.bootkube_env

sudo chmod 755 $HOME/.kube/config
sudo chmod 755 $BOOTKUBE_DIR/.bootkube/tls/*

echo 'Removing any old or stale Armada deployment:'
sudo docker rm -f armada

echo 'Launching OSH using Armada'
#helm init
sudo docker run -d --net host \
  --privileged=true --name armada \
  -v /opt/demo/.bootkube/tls:/opt/demo/.bootkube/tls \
  -v /home/${USER}/.kube/config:/armada/.kube/config \
  -v /opt/demo/manifests:/examples \
  quay.io/charter-ctec/armada:v0.7.1

alias armada="sudo docker exec armada armada"
sleep 3
sudo docker exec armada armada tiller --status
