#!/bin/bash
# Copyright 2017 The Bootkube-CI Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
### Declare colors to use during the running of this script:
declare -r GREEN="\033[0;32m"
declare -r RED="\033[0;31m"
declare -r YELLOW="\033[0;33m"

function echo_green {
  echo -e "${GREEN}$1"; tput sgr0
}
function echo_red {
  echo -e "${RED}$1"; tput sgr0
}
function echo_yellow {
  echo -e "${YELLOW}$1"; tput sgr0
}

HOST_IP=$(ip route get 1 | awk '{print $NF;exit}')
FQDN=$(hostname --fqdn)

source .bootkube_env

echo_green "Installing Docker Compose"

sudo apt install docker-compose

echo_green "Downloading and Extracting Harbor Container Registry"

wget https://github.com/vmware/harbor/releases/download/v1.2.2/harbor-online-installer-v1.2.2.tgz

tar -xzvf harbor-online-installer-v1.2.2.tgz

rm harbor-online-installer-v1.2.2.tgz

echo_green "Editing Harbor Configuration"

sed -i "s/reg.mydomain.com/$FQDN/"    harbor/harbor.cfg

sed -i '/^ui/ s/http/https/' harbor/harbor.cfg

sed -i "s/Harbor12345/$REGISTRY_ADMIN_PASSWORD/" harbor/harbor.cfg

sed -i '/^verify/ s/on/off/' harbor/harbor.cfg

echo_green "Generating Self-signed SSL Certificates"

cd certs

sed -i "s/SERVER_FQDN/$FQDN/" openssl-server.cnf
sed -i "s/HOST_IP/$HOST_IP/" openssl-server.cnf

openssl req -x509 -config openssl-ca.cnf -newkey rsa:4096 -sha256 -nodes -out cacert.pem -outform PEM -subj "/C=US/ST=Colorado/L=Denver/O=Charter Communications/CN=$FQDN"

openssl req -config openssl-server.cnf -newkey rsa:2048 -sha256 -nodes -out servercert.csr -outform PEM -subj "/C=US/ST=Colorado/L=Denver/O=Charter Communications/CN=$FQDN"

touch index.txt

echo '01' > serial.txt

openssl ca -batch -config openssl-ca.cnf -policy signing_policy -extensions signing_req -out servercert.pem -infiles servercert.csr

openssl x509 -in servercert.pem -text -noout

sudo mkdir -p /data/cert

sudo cp servercert.pem /data/cert/server.crt

sudo cp serverkey.pem /data/cert/server.key

sudo mkdir -p /etc/docker/certs.d/$FQDN/

sudo mkdir -p /etc/docker/certs.d/$HOST_IP/

sudo cp cacert.pem /etc/docker/certs.d/$FQDN/domain.crt

sudo cp cacert.pem /etc/docker/certs.d/$HOST_IP/domain.crt

cd ..

echo_green "Installing Harbor with Clair and Notary"

sudo ./harbor/install.sh --with-clair --with-notary


echo_green "Pushing Images to Registry"

sudo docker login $HOST_IP

sudo docker pull ubuntu:latest

sudo docker tag dd6f76d9cc90 $HOST_IP/library/ubuntu:latest

sudo docker push $HOST_IP/library/ubuntu:latest
