#!/bin/bash
# Copyright 2017 Charter DNA Team (CTEC).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
### Declare colors to use during the running of this script:
declare -r GREEN="\033[0;32m"
declare -r RED="\033[0;31m"
declare -r YELLOW="\033[0;33m"

function echo_green {
  echo -e "${GREEN}$1"; tput sgr0
}
function echo_red {
  echo -e "${RED}$1"; tput sgr0
}
function echo_yellow {
  echo -e "${YELLOW}$1"; tput sgr0
}

HOST_IP=$(ip route get 1 | awk '{print $NF;exit}')
FQDN=$(hostname --fqdn)

cd /opt/demo/projects/

sed -i '/DNS.1/d' certs/openssl-server.cnf

sed -i '/IP.1/d' certs/openssl-server.cnf

echo "DNS.1  = SERVER_FQDN" >> certs/openssl-server.cnf

echo "IP.1   = HOST_IP" >> certs/openssl-server.cnf

rm certs/*pem

rm certs/*txt

rm certs/*csr

rm certs/*.attr

rm certs/*.old

sudo rm -rf /etc/docker/certs.d/$FQDN/

sudo rm -rf /etc/docker/certs.d/$HOST_IP/

cd harbor

sudo docker-compose down -v --remove-orphans --rmi all

cd ..

sudo rm -rf /data

sudo docker rmi $HOST_IP/library/ubuntu:latest

sudo rm -rf harbor

