#!/bin/bash
# Copyright 2017 Charter DNA Team (CTEC).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
### Declare colors to use during the running of this script:
declare -r GREEN="\033[0;32m"
declare -r RED="\033[0;31m"
declare -r YELLOW="\033[0;33m"

function echo_green {
  echo -e "${GREEN}$1"; tput sgr0
}
function echo_red {
  echo -e "${RED}$1"; tput sgr0
}
function echo_yellow {
  echo -e "${YELLOW}$1"; tput sgr0
}

source /opt/demo/.bootkube_env

echo_yellow "\nDELETING INFRASTRUCTURE COMPONENTS:"
helm delete --purge osh-ingress
helm delete --purge osh-rabbitmq
helm delete --purge osh-etcd
helm delete --purge osh-libvirt
helm delete --purge osh-openvswitch
helm delete --purge osh-memcached

echo_yellow "\nDELETING OPENSTACK COMPONENTS:"
helm delete --purge osh-horizon
helm delete --purge osh-heat
helm delete --purge osh-cinder
helm delete --purge osh-glance
helm delete --purge osh-keystone
helm delete --purge osh-neutron
helm delete --purge osh-nova

kubectl delete cronjob/`(kubectl get cronjob -n openstack | grep keystone-credential | cut -d " " -f1)` -n openstack
kubectl delete cronjob/`(kubectl get cronjob -n openstack | grep keystone-fernet | cut -d " " -f1)` -n openstack
kubectl delete cronjob/`(kubectl get cronjob -n openstack | grep cinder | cut -d " " -f1)` -n openstack

sudo rm -rf /var/lib/nova
for node in $(cat /opt/demo/deploy-node/nodes); do
  ssh -tq ${node} "sudo rm -rf /var/lib/nova";
done
