---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: helm-toolkit
data:
  chart_name: helm-toolkit
  release: helm-toolkit
  namespace: helm-toolkit
  timeout: 300
  values: {}
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/ocata/helm-toolkit-4.0.2.tgz
    subpath: helm-toolkit
    reference: null
  dependencies: []
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: memcached
data:
  chart_name: memcached
  release: memcached
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/ocata/memcached-4.0.2.tgz
    subpath: memcached
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: etcd
data:
  chart_name: etcd
  release: etcd
  namespace: openstack
  timeout: 3600
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/ocata/etcd-4.0.2.tgz
    subpath: etcd
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: rabbitmq
data:
  chart_name: rabbitmq
  release: rabbitmq
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/ocata/rabbitmq-4.0.2.tgz
    subpath: rabbitmq
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ingress
data:
  chart_name: ingress
  release: ingress
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/ocata/ingress-4.0.2.tgz
    subpath: ingress
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openvswitch
data:
  chart_name: openvswitch
  release: openvswitch
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    network:
      interface:
        external: eth1
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/ocata/openvswitch-4.0.2.tgz
    subpath: openvswitch
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: libvirt
data:
  chart_name: libvirt
  release: libvirt
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/ocata/libvirt-4.0.2.tgz
    subpath: libvirt
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: keystone
data:
  chart_name: keystone
  release: keystone
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    conf:
      keystone:
        identity:
          driver: sql
    images:
      db_sync: quay.io/charter-os/ubuntu-source-keystone:ocata2
      api: quay.io/charter-os/ubuntu-source-keystone:ocata2
    pod:
      replicas:
        api: 3
    dependencies:
      api:
        jobs:
        - keystone-db-sync
      db_sync:
        jobs:
        - keystone-db-init
    bootstrap:
      enabled: false
      script: |
        env
        openstack project create --description 'Charter CTEC' ctec
        openstack user create --password password charter_admin
        openstack role add --user charter_admin --user-domain default --project ctec --project-domain default 'admin'
        openstack project create --description 'Demo Project' demo
        openstack user create --password password demo
        openstack role list
        openstack role add --user demo --user-domain default --project demo --project-domain default "_member_"
    manifests:
      job_db_drop: true
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/ocata/keystone-4.0.2.tgz
    subpath: keystone
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: horizon
data:
  chart_name: horizon
  release: horizon
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    pod:
      replicas:
        server: 2
    images:
      db_sync: quay.io/charter-os/ubuntu-source-horizon:ocata
      horizon: quay.io/charter-os/ubuntu-source-horizon:ocata
    network:
      enable_node_port: true
    manifests:
      job_db_drop: true
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/ocata/horizon-4.0.2.tgz
    subpath: horizon
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: glance
data:
  chart_name: glance
  release: glance
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    dependencies:
      ks_user:
        jobs:
        - keystone-db-sync
      ks_service:
        jobs:
        - keystone-db-sync
      ks_endpoints:
        jobs:
        - keystone-db-sync
    bootstrap:
      enabled: false
    pod:
      user:
        glance:
          uid: 42415
    images:
      db_sync: quay.io/charter-os/ubuntu-source-glance-api:ocata
      api: quay.io/charter-os/ubuntu-source-glance-api:ocata
      registry: quay.io/charter-os/ubuntu-source-glance-registry:ocata
    storage: radosgw
    pod:
      replicas:
        api: 2
        registry: 2
    endpoints:
      identity:
        auth:
          admin:
            username: charter_admin
            project_name: ctec
          user:
            project_name: demo
    manifests:
      job_db_drop: true
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/ocata/glance-4.0.2.tgz
    subpath: glance
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: neutron
data:
  chart_name: neutron
  release: neutron
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    dependencies:
      ks_user:
        jobs:
        - keystone-db-sync
      ks_service:
        jobs:
        - keystone-db-sync
      ks_endpoints:
        jobs:
        - keystone-db-sync
    pod:
      lifecycle:
        upgrades:
          daemonsets:
            ovs_agent:
              enabled: false
      user:
        neutron:
          uid: 42435
      replicas:
        server: 2
    images:
      db_sync: quay.io/charter-os/ubuntu-source-neutron-server:ocata
      server: quay.io/charter-os/ubuntu-source-neutron-server:ocata
      dhcp: quay.io/charter-os/ubuntu-source-neutron-dhcp-agent:ocata
      metadata: quay.io/charter-os/ubuntu-source-neutron-metadata-agent:ocata
      l3: quay.io/charter-os/ubuntu-source-neutron-l3-agent:ocata
    bootstrap:
      enabled: false
      script: |
        openstack network create --share --external --provider-physical-network "public" --provider-network-type vlan --provider-segment '482' provider-482
        openstack subnet create --subnet-range "44.24.8.0/22" --gateway "44.24.8.1" --network provider-482 --allocation-pool start="44.24.8.100",end="44.24.8.250" --dns-nameserver "44.128.12.15" provider-subnet
    network:
      interface:
        external: eth1
    conf:
      neutron:
        DEFAULT:
          l3_ha_network_type: vxlan
      plugins:
        ml2_conf:
          ml2_type_vlan:
            network_vlan_ranges: public:482:482
        openvswitch_agent:
          agent:
            tunnel_types: vxlan
          ovs:
            bridge_mappings: public:br-ex
      metadata_agent:
        DEFAULT:
          nova_metadata_ip: 10.96.120.234
    endpoints:
      identity:
        auth:
          admin:
            username: charter_admin
            project_name: ctec
          user:
            project_name: demo
          nova:
            project_name: demo
    manifests:
      job_db_drop: true
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/ocata/neutron-4.0.2.tgz
    subpath: neutron
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: nova
data:
  chart_name: nova
  release: nova
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    dependencies:
      ks_user:
        jobs:
        - keystone-db-sync
      ks_service:
        jobs:
        - keystone-db-sync
      ks_endpoints:
        jobs:
        - keystone-db-sync
    pod:
      user:
        nova:
          uid: 42436
    images:
      dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
      tags:
        db_sync: quay.io/charter-os/ubuntu-source-nova-api:ocata
        api: quay.io/charter-os/ubuntu-source-nova-api:ocata
        conductor: quay.io/charter-os/ubuntu-source-nova-conductor:ocata
        scheduler: quay.io/charter-os/ubuntu-source-nova-scheduler:ocata
        novncproxy: quay.io/charter-os/ubuntu-source-nova-novncproxy:ocata
        novncproxy_assets: quay.io/charter-os/ubuntu-source-nova-novncproxy:ocata
        consoleauth: quay.io/charter-os/ubuntu-source-nova-consoleauth:ocata
        compute: quay.io/charter-os/ubuntu-source-nova-compute:ocata
        compute_ssh: quay.io/charter-os/ubuntu-source-nova-ssh:ocata
        placement: quay.io/charter-os/ubuntu-source-nova-placement-api:ocata
    conf:
      nova:
        libvirt:
          virt_type: qemu
    bootstrap:
      enabled: false
      flavors:
        options:
          vnf_tiny:
              name: "vnf.tiny"
              id: "auto"
              ram: 512
              disk: 1
              vcpus: 1
          vnf_small:
              name: "vnf.small"
              id: "auto"
              ram: 2048
              disk: 20
              vcpus: 1
          vnf_medium:
              name: "vnf.medium"
              id: "auto"
              ram: 4096
              disk: 40
              vcpus: 2
          vnf_large:
              name: "vnf.large"
              id: "auto"
              ram: 8192
              disk: 80
              vcpus: 4
          vnf_xlarge:
              name: "vnf.xlarge"
              id: "auto"
              ram: 16384
              disk: 160
              vcpus: 8
    network:
      metadata:
        ip: 10.96.120.234
    manifests:
      job_db_drop: true
    endpoints:
      identity:
        auth:
          admin:
            username: charter_admin
            project_name: ctec
          user:
            project_name: demo
          neutron:
            project_name: demo
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/ocata/nova-4.0.2.tgz
    subpath: nova
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: cinder
data:
  chart_name: cinder
  release: cinder
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    dependencies:
      ks_user:
        jobs:
        - keystone-db-sync
      ks_service:
        jobs:
        - keystone-db-sync
      ks_endpoints:
        jobs:
        - keystone-db-sync
    bootstrap:
      enabled: false
    pod:
      user:
        cinder:
          uid: 42407
    images:
      db_sync: quay.io/charter-os/ubuntu-source-cinder-api:ocata
      api: quay.io/charter-os/ubuntu-source-cinder-api:ocata
      scheduler: quay.io/charter-os/ubuntu-source-cinder-scheduler:ocata
      volume: quay.io/charter-os/ubuntu-source-cinder-volume:ocata
      volume_usage_audit: quay.io/charter-os/ubuntu-source-cinder-volume:ocata
    pod:
      replicas:
        api: 2
    endpoints:
      identity:
        auth:
          admin:
            username: charter_admin
            project_name: ctec
          user:
            project_name: demo
    manifests:
      job_db_drop: true
      deployment_backup: false
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/ocata/cinder-4.0.2.tgz
    subpath: cinder
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: heat
data:
  chart_name: heat
  release: heat
  namespace: openstack
  timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    dependencies:
      ks_user:
        jobs:
        - keystone-db-sync
      ks_service:
        jobs:
        - keystone-db-sync
      ks_endpoints:
        jobs:
        - keystone-db-sync
    pod:
      user:
        heat:
          uid: 42418
    images:
      db_sync: quay.io/charter-os/ubuntu-source-heat-api:ocata
      api: quay.io/charter-os/ubuntu-source-heat-api:ocata
      cfn: quay.io/charter-os/ubuntu-source-heat-api:ocata
      cloudwatch: quay.io/charter-os/ubuntu-source-heat-api:ocata
      engine: quay.io/charter-os/ubuntu-source-heat-engine:ocata
    manifests:
      job_db_drop: true
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/ocata/heat-4.0.2.tgz
    subpath: heat
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-infra-services
data:
  description: "OpenStack Infra Services"
  sequenced: False
  chart_group:
    - etcd
    - rabbitmq
    - memcached
    - ingress
    - libvirt
    - openvswitch
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-components
data:
  description: "OpenStack Components"
  sequenced: False
  chart_group:
    - keystone
    - horizon
    - glance
    - neutron
    - nova
    - cinder
    - heat
---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: armada-manifest
data:
  release_prefix: osh
  chart_groups:
    - openstack-infra-services
    - openstack-components
